name: Deploy React and FastAPI to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: simple-docker-service-06f80b744a75
  ECS_CLUSTER: fastapi-cluster
  ECS_SERVICE: fastapi-service
  ECS_TASK_DEFINITION: fastapi-task
  S3_BUCKET: fastapi-react-frontend-710562346725
  CLOUDFRONT_DISTRIBUTION_ID: E7EUBD0LFAZ17

jobs:

  frontend:
    name: Deploy React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React application
        working-directory: frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::710562346725:role/GitHubActionsDeploymentRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy React to S3
        run: |
          aws s3 sync frontend/build/ s3://${{ env.S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"


  backend:
    name: Deploy FastAPI Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::710562346725:role/GitHubActionsDeploymentRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:latest .

      - name: Tag Docker image
        run: |
          docker tag \
            ${{ env.ECR_REPOSITORY }}:latest \
            710562346725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
            710562346725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ env.ECS_SERVICE }}" \
            --force-new-deployment
